/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KalbisPuskes.gui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author AiVarelEzel
 */
public class Pembayaran extends javax.swing.JFrame {
    public int penampung_total;
    private static Connection koneksi;
    Connection con = null;
    ResultSet rs = null;
    Statement st = null;
    PreparedStatement pst = null;
    String ID = Login_Petugas.getUserLogin();
    
    /**
     * Creates new form Pembayaran
     */
    
    public Pembayaran() {
        initComponents();
        this.setLocationRelativeTo(null);
        con=Connect.ConnectDb();
        buttonGroup.add(rbAsuransi);
        buttonGroup.add(rbDebit);
        buttonGroup.add(rbTunai);
        nama_user.setText("Login as: "+ID);
        TanggalSekarang();
    }
    
    public void TanggalSekarang(){     
        Thread clock = new Thread(){
            public void run(){
                for(;;){
                   Calendar cal = new GregorianCalendar();
                    int hari = cal.get(Calendar.DAY_OF_WEEK);
                    int tanggal = cal.get(Calendar.DAY_OF_MONTH);
                    int bulan = cal.get(Calendar.MONTH);
                    int tahun = cal.get(Calendar.YEAR);
                    int jam = cal.get(Calendar.HOUR_OF_DAY);
                    int menit = cal.get(Calendar.MINUTE);
                    int detik = cal.get(Calendar.SECOND);
                    tgl_transaksi2.setText("Tanggal Transaksi: "+tanggal+"-"+(bulan+1)+"-"+tahun+"   Waktu: "+jam+":"+(menit)+":"+detik);
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };        
        clock.start();        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kode_transaksi = new javax.swing.JTextField();
        rbAsuransi = new javax.swing.JRadioButton();
        rbDebit = new javax.swing.JRadioButton();
        rbTunai = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        total_tagihan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nomor_rekam_medis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        no_registrasi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nama_pasien = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbKonsultasi = new javax.swing.JCheckBox();
        cbDarah = new javax.swing.JCheckBox();
        total_harga = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        total_harga_resep = new javax.swing.JLabel();
        cbUrin = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        tindakan = new javax.swing.JTextField();
        kode_rawat_inap = new javax.swing.JLabel();
        kode_resep = new javax.swing.JTextField();
        bHitung = new javax.swing.JButton();
        jumlah_bayar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        kembali = new javax.swing.JTextField();
        bSimpan = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        nama_user = new javax.swing.JLabel();
        panel_struk = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        kode_transaksi1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nama_pasien1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        no_registrasi1 = new javax.swing.JLabel();
        total_tagihan1 = new javax.swing.JLabel();
        kembali1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jumlah_bayar1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tgl_transaksi1 = new javax.swing.JLabel();
        bPrint = new javax.swing.JButton();
        tgl_transaksi2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PEMBAYARAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kode Transaksi");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Jenis Bayar");

        kode_transaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kode_transaksiKeyTyped(evt);
            }
        });

        rbAsuransi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbAsuransi.setText("Asuransi");
        rbAsuransi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAsuransiActionPerformed(evt);
            }
        });

        rbDebit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbDebit.setText("Debit");
        rbDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDebitActionPerformed(evt);
            }
        });

        rbTunai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbTunai.setText("Tunai");
        rbTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTunaiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Total Tagihan");

        total_tagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_tagihanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("No. Rekam Medis");

        nomor_rekam_medis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomor_rekam_medisKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("No. Registrasi");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nama Depan Pasien");

        nama_pasien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Kode Rawat Inap");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Total Harga Obat");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Jumlah Bayar");

        cbKonsultasi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbKonsultasi.setText("Konsultasi");
        cbKonsultasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKonsultasiActionPerformed(evt);
            }
        });

        cbDarah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbDarah.setText("Ambil Darah");
        cbDarah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDarahActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Kode Resep");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tindakan");

        cbUrin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbUrin.setText("Tes Urin");
        cbUrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUrinActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Total Harga");

        tindakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tindakanActionPerformed(evt);
            }
        });
        tindakan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tindakanInputMethodTextChanged(evt);
            }
        });
        tindakan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tindakanKeyReleased(evt);
            }
        });

        kode_rawat_inap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        kode_resep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_resepActionPerformed(evt);
            }
        });
        kode_resep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kode_resepKeyReleased(evt);
            }
        });

        bHitung.setText("Hitung");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });

        jumlah_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_bayarActionPerformed(evt);
            }
        });
        jumlah_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlah_bayarKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Rp.");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Kembali");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Rp.");

        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Rp.");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("PUSKESMAS SEHAT");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Kode Transaksi");

        kode_transaksi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kode_transaksi1KeyReleased(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("No. Registrasi");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Nama Depan Pasien");

        nama_pasien1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Total Tagihan");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Rp.");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Jumlah Bayar");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Rp.");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Kembali");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Rp.");

        total_tagihan1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        kembali1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel34.setText("Terima kasih telah mempercayakan pelayanan kesehatan anda kepada kami");

        jumlah_bayar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_bayar1ActionPerformed(evt);
            }
        });
        jumlah_bayar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlah_bayar1KeyReleased(evt);
            }
        });

        jLabel20.setText("Tgl. Transaksi");

        javax.swing.GroupLayout panel_strukLayout = new javax.swing.GroupLayout(panel_struk);
        panel_struk.setLayout(panel_strukLayout);
        panel_strukLayout.setHorizontalGroup(
            panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_strukLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_strukLayout.createSequentialGroup()
                        .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(37, 46, Short.MAX_VALUE)
                        .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kode_transaksi1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(nama_pasien1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(no_registrasi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44))
                    .addGroup(panel_strukLayout.createSequentialGroup()
                        .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29))
                        .addGap(43, 43, 43)
                        .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_strukLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(total_tagihan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(55, 55, 55))
                            .addGroup(panel_strukLayout.createSequentialGroup()
                                .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_strukLayout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(18, 18, 18)
                                        .addComponent(kembali1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panel_strukLayout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jumlah_bayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(47, 47, 47))))
                    .addGroup(panel_strukLayout.createSequentialGroup()
                        .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel34)
                            .addComponent(jLabel31))
                        .addGap(0, 49, Short.MAX_VALUE))))
            .addGroup(panel_strukLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_strukLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tgl_transaksi1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_strukLayout.setVerticalGroup(
            panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_strukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(13, 13, 13)
                .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(tgl_transaksi1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_strukLayout.createSequentialGroup()
                        .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(kode_transaksi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(no_registrasi1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(nama_pasien1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)))
                    .addComponent(total_tagihan1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jumlah_bayar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_strukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(jLabel32))
                    .addComponent(kembali1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(34, 34, 34))
        );

        bPrint.setText("PRINT");
        bPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPrintActionPerformed(evt);
            }
        });

        tgl_transaksi2.setText("jLabel21");

        jMenu1.setText("Koneksi");

        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Navigasi");

        jMenuItem2.setText("Home");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenu3.setText("Pasien");

        jMenuItem3.setText("Data Pasien");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenu2.add(jMenu3);

        jMenu4.setText("Obat");

        jMenuItem5.setText("Data Obat");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenu2.add(jMenu4);

        jMenu5.setText("Administrasi");

        jMenuItem7.setText("Rawat Inap");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(bPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(cbKonsultasi)
                                .addGap(18, 18, 18)
                                .addComponent(cbDarah)
                                .addGap(18, 18, 18)
                                .addComponent(cbUrin))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rbAsuransi)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbDebit)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbTunai))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(total_tagihan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                                .addComponent(total_harga, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(total_harga_resep, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(kode_rawat_inap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(kode_resep, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(nama_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(86, 86, 86)
                                .addComponent(tindakan, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kode_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(nomor_rekam_medis)
                                    .addComponent(no_registrasi)))
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jumlah_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addComponent(panel_struk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tgl_transaksi2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(455, 455, 455)
                        .addComponent(nama_user, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nama_user, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(tgl_transaksi2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(kode_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nomor_rekam_medis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(no_registrasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(nama_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(tindakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(kode_rawat_inap, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(kode_resep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total_harga_resep, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbKonsultasi)
                            .addComponent(cbDarah)
                            .addComponent(cbUrin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(total_tagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rbAsuransi)
                            .addComponent(rbDebit)
                            .addComponent(rbTunai))
                        .addGap(18, 18, 18)
                        .addComponent(bHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jumlah_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_struk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void total_tagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_tagihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_tagihanActionPerformed

    private void cbKonsultasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKonsultasiActionPerformed
        // TODO add your handling code here:
        
        if(cbKonsultasi.isSelected()){
            penampung_total = penampung_total+50000;
        }else{
            penampung_total = penampung_total-50000;
        }
        
        total_harga.setText(String.valueOf(penampung_total));
        
    }//GEN-LAST:event_cbKonsultasiActionPerformed

    private void rbAsuransiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAsuransiActionPerformed
        // TODO add your handling code here:
        jenis_bayar ="Asuransi";
    }//GEN-LAST:event_rbAsuransiActionPerformed

    private void cbDarahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDarahActionPerformed
        // TODO add your handling code here:
        if(cbDarah.isSelected()){
            penampung_total = penampung_total+50000;
        }else{
            penampung_total = penampung_total-50000;
        }
        total_harga.setText(String.valueOf(penampung_total));
    }//GEN-LAST:event_cbDarahActionPerformed

    private void cbUrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUrinActionPerformed
        // TODO add your handling code here:
        if(cbUrin.isSelected()){
            penampung_total = penampung_total+50000;
        }else{
            penampung_total = penampung_total-50000;
        }
        
        total_harga.setText(String.valueOf(penampung_total));
    }//GEN-LAST:event_cbUrinActionPerformed

    private void nomor_rekam_medisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomor_rekam_medisKeyReleased
        // TODO add your handling code here:
        try {            
                st = con.createStatement();
                String sql = "select * from rekam_medis where nomor_rekam_medis='"+this.nomor_rekam_medis.getText()+"'";
                try ( ResultSet r = st.executeQuery(sql)) {
                    while (rs.next()) {
                        no_registrasi.setText(r.getString("no_registrasi"));
                        nama_pasien.setText(r.getString("nama_pasien"));
                        tindakan.setText(r.getString("tindakan"));
                        kode_rawat_inap.setText(r.getString("kode_rawat_inap"));
                        kode_resep.setText(r.getString("kode_resep"));                        
                    }
                }
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan "+e.getMessage());
        }
        String cekLength;
        String nomorfix;
        DateFormat fmtTahun = new SimpleDateFormat("yyyy");
        DateFormat fmtBulan = new SimpleDateFormat("MM");
        DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat fmtIndo = new SimpleDateFormat("dd-MM-yyyy");
        String nowTahun = fmtTahun.format(new Date());
        String nowBulan = fmtBulan.format(new Date());
        String now = fmt.format(new Date());
        String nowIndo = fmtIndo.format(new Date());
        Integer nomorTerakhir;
        
       
    }//GEN-LAST:event_nomor_rekam_medisKeyReleased

    private void tindakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tindakanActionPerformed
        // TODO add your handling code here:
        try {            
                st = con.createStatement();
                String sql = "select * from rekam_medis where tindakan='"+this.tindakan.getText()+"'";
                try ( ResultSet r = st.executeQuery(sql)) {
                    String tindak = String.valueOf(tindakan.getText());
                    if("Rawat Inap".equals(tindak)){
                        penampung_total = penampung_total+100000;
                    } else {
                       penampung_total = penampung_total-100000;
                    }
                     total_harga.setText(String.valueOf(penampung_total));
                }
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan "+e.getMessage());
        }
    }//GEN-LAST:event_tindakanActionPerformed

    private void tindakanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tindakanKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tindakanKeyReleased

    private void kode_resepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_resepKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_kode_resepKeyReleased

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        // TODO add your handling code here:
        int total;
        int harga_obat;
        int harga;
        
        harga_obat= Integer.valueOf(total_harga_resep.getText());
        harga= Integer.valueOf(total_harga.getText());
        total = harga_obat+harga;
        String jadi = String.valueOf(total);
        total_tagihan.setText(jadi);
    }//GEN-LAST:event_bHitungActionPerformed

    private void tindakanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tindakanInputMethodTextChanged
        // TODO add your handling code here:
        try {            
                st = con.createStatement();
                String sql = "select * from rekam_medis where tindakan='"+this.tindakan.getText()+"'";
                try (ResultSet r = st.executeQuery(sql)) {
                    String tindak = String.valueOf(tindakan.getText());
                    if("Rawat Inap".equals(tindak)){
                        penampung_total = penampung_total+100000;
                    } else {
                       penampung_total = penampung_total-100000;
                    }
                     total_harga.setText(String.valueOf(penampung_total));
                }
        }catch(SQLException e) {

            System.out.println("Terjadi kesalahan "+e.getMessage());

        }
    }//GEN-LAST:event_tindakanInputMethodTextChanged

    private void kode_resepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_resepActionPerformed
        // TODO add your handling code here:
        try {            
            st = con.createStatement();
            String sql = "select * from resep where kode_resep='"+this.kode_resep.getText()+"'";

                try (ResultSet r = st.executeQuery(sql)) {
                    while (r.next()) {
                        total_harga_resep.setText(r.getString("total_harga_resep"));                        
                    }
                }
        }catch(SQLException e) {

            System.out.println("Terjadi kesalahan "+e.getMessage());

        }
    }//GEN-LAST:event_kode_resepActionPerformed

    private void jumlah_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_bayarActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void jumlah_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah_bayarKeyReleased
        // TODO add your handling code here:
        int total;
        int tagihan;
        int bayar;
        
        tagihan= Integer.valueOf(total_tagihan.getText());
        bayar= Integer.valueOf(jumlah_bayar.getText());
        total = tagihan-bayar;
        String jadi = String.valueOf(total);
        kembali.setText(jadi);
    }//GEN-LAST:event_jumlah_bayarKeyReleased

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        try{
            String value1 = kode_transaksi.getText();
            String value2 = nomor_rekam_medis.getText();
            String value3 = no_registrasi.getText();
            String value4 = nama_pasien.getText();
            String value6 = tindakan.getText();
            String value7 = kode_rawat_inap.getText();
            String value8 = kode_resep.getText();
            String value9 = total_harga_resep.getText();
            String value10 = jenis_bayar;
            String value11 = total_tagihan.getText();
            String value12 = ID;
            
            koneksi.createStatement().execute("insert into pembayaran values('"+value1+"','"+value2+"','"+value3+"','"+value4+"','"+value6+"','"+value7+"','"+value8+"','"+value9+"','"+value10+"','"+value11+"',DATE_FORMAT(NOW(),'%Y-%m-%d %T'),'"+value12+"')");
            JOptionPane.showMessageDialog(rootPane, "Data Tersimpan!");
        }catch (SQLException | HeadlessException e){
        System.out.println(e);
        JOptionPane.showMessageDialog(null,e);
        }        
    }//GEN-LAST:event_bSimpanActionPerformed

    private void rbDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDebitActionPerformed
        // TODO add your handling code here:
        jenis_bayar = "Debit";
    }//GEN-LAST:event_rbDebitActionPerformed

    private void rbTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTunaiActionPerformed
        // TODO add your handling code here:
        jenis_bayar = "Tunai";
    }//GEN-LAST:event_rbTunaiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login_Petugas().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Pasien().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Rawat_Inap().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Obat().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void bPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPrintActionPerformed
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
     job.setJobName("panel_struk");

     job.setPrintable (new Printable() {    
        public int print(Graphics pg, PageFormat pf, int pageNum){
            if (pageNum > 0){
            return Printable.NO_SUCH_PAGE;
            }

            Graphics2D g2 = (Graphics2D) pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            panel_struk.print(g2);
            return Printable.PAGE_EXISTS;
        }
     });
     boolean ok = job.printDialog();
     if (ok) {
         try {
              job.print();
         } catch (PrinterException ex) {
               
         }
     }
    }//GEN-LAST:event_bPrintActionPerformed

    private void jumlah_bayar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_bayar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_bayar1ActionPerformed

    private void jumlah_bayar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah_bayar1KeyReleased
        // TODO add your handling code here:
        int total;
        int tagihan;
        int bayar;
        
        tagihan= Integer.valueOf(total_tagihan1.getText());
        bayar= Integer.valueOf(jumlah_bayar1.getText());
        total = tagihan-bayar;
        String jadi = String.valueOf(total);
        kembali1.setText(jadi);
    }//GEN-LAST:event_jumlah_bayar1KeyReleased

    private void kode_transaksi1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_transaksi1KeyReleased
        // TODO add your handling code here:
        try {            
                st = con.createStatement();
                String sql = "select * from pembayaran where kode_transaksi='"+this.kode_transaksi1.getText()+"'";
                try (ResultSet r = st.executeQuery(sql)) {
                    while (r.next()) {
                        no_registrasi1.setText(r.getString("no_registrasi"));
                        nama_pasien1.setText(r.getString("nama_pasien"));
                        total_tagihan1.setText(r.getString("total_tagihan"));
                        tgl_transaksi1.setText(r.getString("tgl_transaksi"));
                    }
            }
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan "+e.getMessage());
        }
    }//GEN-LAST:event_kode_transaksi1KeyReleased

    private void kode_transaksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_transaksiKeyTyped
        // TODO add your handling code here:
        if(kode_transaksi.getText().length()>=10){  
           evt.consume();
        }
    }//GEN-LAST:event_kode_transaksiKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bPrint;
    private javax.swing.JButton bSimpan;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JCheckBox cbDarah;
    private javax.swing.JCheckBox cbKonsultasi;
    private javax.swing.JCheckBox cbUrin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JTextField jumlah_bayar;
    private javax.swing.JTextField jumlah_bayar1;
    private javax.swing.JTextField kembali;
    private javax.swing.JLabel kembali1;
    private javax.swing.JLabel kode_rawat_inap;
    private javax.swing.JTextField kode_resep;
    private javax.swing.JTextField kode_transaksi;
    private javax.swing.JTextField kode_transaksi1;
    private javax.swing.JLabel nama_pasien;
    private javax.swing.JLabel nama_pasien1;
    private javax.swing.JLabel nama_user;
    private javax.swing.JTextField no_registrasi;
    private javax.swing.JLabel no_registrasi1;
    private javax.swing.JTextField nomor_rekam_medis;
    private javax.swing.JPanel panel_struk;
    private javax.swing.JRadioButton rbAsuransi;
    private javax.swing.JRadioButton rbDebit;
    private javax.swing.JRadioButton rbTunai;
    private javax.swing.JLabel tgl_transaksi1;
    private javax.swing.JLabel tgl_transaksi2;
    private javax.swing.JTextField tindakan;
    private javax.swing.JTextField total_harga;
    private javax.swing.JLabel total_harga_resep;
    private javax.swing.JTextField total_tagihan;
    private javax.swing.JLabel total_tagihan1;
    // End of variables declaration//GEN-END:variables
private String jenis_bayar;
}
