/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KalbisPuskes.gui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import java.awt.print.*;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JTable;
/**
 *
 * @author AiVarelEzel
 */
public class Resep extends javax.swing.JFrame {
    private static Connection koneksi;
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public int jumlah_obat;
    public int harga_obat;
    public int total_harga_obat;
    String ID = Login_Dokter.getUserLogin();

    /**
     * Creates new form Resep
     */
    public Resep() {
        initComponents();
        con=Connect.ConnectDb();
        setuptable();
        this.setLocationRelativeTo(null);
        total_harga_resep.setVisible(false);
        harga_satuan.setVisible(false);
        nama_user.setText("Login as:"+ID);
        TanggalSekarang();
    }
    
    public void TanggalSekarang(){     
        Thread clock = new Thread(){
            public void run(){
                for(;;){
                    Calendar cal = new GregorianCalendar();
                    int tanggal = cal.get(Calendar.DAY_OF_MONTH);
                    int bulan = cal.get(Calendar.MONTH);
                    int tahun = cal.get(Calendar.YEAR);
                    java.util.Date d = new java.util.Date();
                    String dayweek = "EEEE";
                    SimpleDateFormat sdf = new SimpleDateFormat(dayweek);
                    
                    tgl_resep.setText(""+sdf.format(d)+", "+tanggal+" / "+(bulan+1)+" / "+tahun);
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };        
        clock.start();        
    }
    
    public Connection koneksi() throws SQLException{
        if (koneksi==null) {
            try {
                String url="jdbc:mysql://localhost:3306/puskesmas"; //nama database
                String user="root"; //user mysql
                String password=""; //password mysql
                DriverManager.registerDriver(new com.mysql.jdbc.Driver());
                koneksi=DriverManager.getConnection(url,user,password);
            }catch (SQLException e) {
                System.out.println("Error membuat koneksi");
            }
        }
     return koneksi;
    }
    
    public void setuptable(){
        try
        {
            String sql = "select kode_resep AS 'Kode Resep',no_registrasi AS 'No. Registrasi',nama_pasien as 'Nama Pasien',kode_obat as 'Kode Obat',nama_obat as 'Nama Obat',jumlah as Jumlah,tgl_resep as 'Tanggal Resep',kode_dokter as 'Kode Dokter',nama_dokter as 'Nama Dokter' from resep";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            tabel_resep.setModel(DbUtils.resultSetToTableModel(rs));
            //To remove previously added rows
        }
        catch(  SQLException e)
        {
           JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_resep = new javax.swing.JTable();
        panel_resep = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kode_resep = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama_obat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nama_dokter = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        no_registrasi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nama_pasien = new javax.swing.JTextField();
        kode_obat = new javax.swing.JTextField();
        kode_dokter = new javax.swing.JTextField();
        tgl_resep = new javax.swing.JLabel();
        bSimpan = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        total_harga_resep = new javax.swing.JTextField();
        harga_satuan = new javax.swing.JTextField();
        nama_user = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setText("RESEP");

        tabel_resep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_resep);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Kode Resep");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kode Obat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nama Obat");

        nama_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_obatActionPerformed(evt);
            }
        });
        nama_obat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nama_obatKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah");

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tanggal Resep");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Kode Dokter");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nama Dokter");

        nama_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_dokterActionPerformed(evt);
            }
        });
        nama_dokter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nama_dokterKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("No. Registrasi");

        no_registrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_registrasiActionPerformed(evt);
            }
        });
        no_registrasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                no_registrasiKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nama Pasien");

        nama_pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_pasienActionPerformed(evt);
            }
        });
        nama_pasien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nama_pasienKeyReleased(evt);
            }
        });

        kode_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_obatActionPerformed(evt);
            }
        });
        kode_obat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kode_obatKeyReleased(evt);
            }
        });

        kode_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_dokterActionPerformed(evt);
            }
        });
        kode_dokter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kode_dokterKeyReleased(evt);
            }
        });

        tgl_resep.setText("jLabel11");

        javax.swing.GroupLayout panel_resepLayout = new javax.swing.GroupLayout(panel_resep);
        panel_resep.setLayout(panel_resepLayout);
        panel_resepLayout.setHorizontalGroup(
            panel_resepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resepLayout.createSequentialGroup()
                .addGroup(panel_resepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(kode_dokter, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama_pasien, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_resepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_resepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(no_registrasi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_resepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_resepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nama_dokter, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_resepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel_resepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jumlah)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_resepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panel_resepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel3)
                                                    .addComponent(kode_resep)
                                                    .addComponent(jLabel5)
                                                    .addComponent(nama_obat, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                    .addComponent(jLabel2)
                                                    .addComponent(kode_obat))
                                                .addComponent(jLabel6))
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addComponent(jLabel9)))
                                .addComponent(jLabel4)))
                        .addComponent(jLabel10))
                    .addComponent(tgl_resep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_resepLayout.setVerticalGroup(
            panel_resepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resepLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kode_resep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(no_registrasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kode_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgl_resep, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addComponent(kode_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bUbah.setText("UBAH");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bClear.setText("CLEAR");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        jMenu1.setText("Koneksi");

        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Navigasi");

        jMenuItem2.setText("Rekam Medis");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");

        jMenuItem3.setText("Print");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(bSimpan)
                .addGap(164, 164, 164)
                .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bHapus)
                .addGap(18, 18, 18)
                .addComponent(bClear)
                .addGap(449, 449, 449))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(total_harga_resep, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(harga_satuan))
                    .addComponent(panel_resep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nama_user, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total_harga_resep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(nama_user, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_resep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_obatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nama_obatActionPerformed

    private void nama_obatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nama_obatKeyReleased
        // TODO add your handling code here:
        try {
            Connection c = koneksi();
            try (Statement s = c.createStatement()){
                String sql = "select * from obat where nama_obat='"+this.nama_obat.getText()+"'";
                    try (ResultSet r = s.executeQuery(sql)) {
                        while (r.next()) {
                            kode_obat.setText(r.getString("kode_obat"));                     
                            harga_satuan.setText(r.getString("harga_satuan"));
                        }
                    }
            }
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan "+e.getMessage());
        }
    }//GEN-LAST:event_nama_obatKeyReleased

    private void nama_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_dokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_dokterActionPerformed

    private void nama_dokterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nama_dokterKeyReleased
        // TODO add your handling code here:
        try {
            Connection c = koneksi();
            try (Statement s = c.createStatement()) {
                String sql = "select * from dokter where nama_dokter='"+this.nama_dokter.getText()+"'";
                    try (ResultSet r = s.executeQuery(sql)) {
                        while (r.next()) {
                            kode_dokter.setText(r.getString("kode_dokter"));
                        }
                    }
            }
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan "+e.getMessage());
        }
    }//GEN-LAST:event_nama_dokterKeyReleased

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql ="insert into resep (kode_resep,no_registrasi,nama_pasien,kode_obat,nama_obat,harga_satuan,jumlah,"
                    + "total_harga_resep,tgl_resep,kode_dokter,nama_dokter) values (?,?,?,?,?,?,?,?,DATE_FORMAT(NOW(),'%Y-%m-%d %T'),?)";
            pst=con.prepareStatement(sql);
            pst.setString(1, kode_resep.getText());
            pst.setString(2, no_registrasi.getText());
            pst.setString(3, nama_pasien.getText());
            pst.setString(4, kode_obat.getText());
            pst.setString(5, nama_obat.getText());
            pst.setString(6, harga_satuan.getText());
            pst.setString(7, jumlah.getText());
            pst.setString(8, total_harga_resep.getText());
            //pst.setString(9, ((JTextField)tgl_resep.getDateEditor().getUiComponent()).getText());
            pst.setString(9, nama_dokter.getText());            
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Data Tersimpan!");
        }catch (SQLException | HeadlessException e){
        System.out.println(e);
        JOptionPane.showMessageDialog(null,e);
        }
        try{
            String value1 = jumlah.getText();
            String value2 = kode_obat.getText();
            koneksi.createStatement().execute("update obat set stok = stok - '"+value1+"' Where kode_obat= '"+value2+"' ");
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        setuptable();        
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here
        
        kode_resep.setText("");
        no_registrasi.setText("");
        nama_pasien.setText("");
        kode_obat.setText("");
        nama_obat.setText("");
        jumlah.setText("");
        kode_dokter.setText("");
        nama_dokter.setText("");
    }//GEN-LAST:event_bClearActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Print_Resep().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
    int p = JOptionPane.showConfirmDialog(null, "Anda yakin ingin mengubah data?","Update Data",JOptionPane.YES_NO_OPTION);
    if(p==0){
        String sql = "delete from resep where kode_resep = ?";
        try{
            pst = con.prepareStatement(sql);
            pst.setString(1, kode_resep.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Terhapus");
        }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
        }
        setuptable();
    }
    }//GEN-LAST:event_bHapusActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jumlahActionPerformed

    private void no_registrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_registrasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_registrasiActionPerformed

    private void no_registrasiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_registrasiKeyReleased
        // TODO add your handling code here:
        try {
            Connection c = koneksi();
            try (Statement s = c.createStatement()) {
            String sql = "Select * From pasien Where no_registrasi='"+this.no_registrasi.getText()+"'";
                try (ResultSet r = s.executeQuery(sql)) {
                    while (r.next()) {
                        nama_pasien.setText(r.getString("nama_pasien"));                     
                    }
                }
            }
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan "+e.getMessage());
        }
    }//GEN-LAST:event_no_registrasiKeyReleased

    private void nama_pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_pasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_pasienActionPerformed

    private void nama_pasienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nama_pasienKeyReleased
        // TODO add your handling code here:
        try {
            Connection c = koneksi();
            try (Statement s = c.createStatement()) {
                String sql = "select * from pasien Where nama_pasien='"+this.nama_pasien.getText()+"'";
                    try (ResultSet r = s.executeQuery(sql)){
                        while (r.next()) {
                            no_registrasi.setText(r.getString("no_registrasi"));
                        }
                    }
            }
        }catch(SQLException e) {
           System.out.println("Terjadi kesalahan "+e.getMessage());
        }
    }//GEN-LAST:event_nama_pasienKeyReleased

    private void jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyReleased
        // TODO add your handling code here:
        harga_obat = Integer.valueOf(harga_satuan.getText());
        jumlah_obat = Integer.valueOf(jumlah.getText());
        total_harga_obat= jumlah_obat*harga_obat;
        String ini = String.valueOf(total_harga_obat);
        total_harga_resep.setText(ini);
    }//GEN-LAST:event_jumlahKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login_Dokter().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new RekamMedis().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        // TODO add your handling code here:
    int p = JOptionPane.showConfirmDialog(null, "Anda yakin ingin mengubah data?","Update Data",JOptionPane.YES_NO_OPTION);
    if(p==0){
        try{
            String value1 = kode_resep.getText();
            String value2 = no_registrasi.getText();
            String value3 = nama_pasien.getText();
            String value4 = kode_obat.getText();
            String value5 = nama_obat.getText();
            String value6 = jumlah.getText();
            String value7 = total_harga_resep.getText();
            //String value8 = ((JTextField)tgl_resep.getDateEditor().getUiComponent()).getText();
            String value9 = kode_dokter.getText();
            String value10 = nama_dokter.getText();
            koneksi.createStatement().execute("update obat set kode_resep ='"+value1+"', no_registrasi='"+value2+"', nama_pasien='"+value3+"', kode_obat='"+value4+"', nama_obat='"+value5+"', jumlah='"+value6+"', total_harga_resep='"+value7+"', DATE_FORMAT(NOW(),'%Y-%m-%d %T'), kode_dokter='"+value9+"', nama_dokter='"+value10+"' where kode_resep='"+value1+"' ");
            JOptionPane.showMessageDialog(rootPane,"Data Terupdate!");   
        } catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
        }
        setuptable();
    }
    }//GEN-LAST:event_bUbahActionPerformed

    private void kode_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_obatActionPerformed

    private void kode_obatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_obatKeyReleased
        // TODO add your handling code here:
        try {
            Connection c = koneksi();
            try (Statement s = c.createStatement()) {
                String sql = "select * from obat where kode_obat='"+this.kode_obat.getText()+"'";

                    try (ResultSet r = s.executeQuery(sql)) {
                        while (r.next()) {
                            nama_obat.setText(r.getString("nama_obat"));                     
                            harga_satuan.setText(r.getString("harga_satuan"));
                        }
                    }
            }
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan "+e.getMessage());
        }
    }//GEN-LAST:event_kode_obatKeyReleased

    private void kode_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_dokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_dokterActionPerformed

    private void kode_dokterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_dokterKeyReleased
        // TODO add your handling code here:
        try {
            Connection c = koneksi();
            try (Statement s = c.createStatement()) {
                String sql = "select * from dokter where kode_dokter='"+this.kode_dokter.getText()+"'";
                    try (ResultSet r = s.executeQuery(sql)) {
                        while (r.next()) {
                            nama_dokter.setText(r.getString("nama_dokter"));    
                        }
                    }
            }
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan "+e.getMessage());
        }
    }//GEN-LAST:event_kode_dokterKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClear;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bUbah;
    private javax.swing.JTextField harga_satuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kode_dokter;
    private javax.swing.JTextField kode_obat;
    private javax.swing.JTextField kode_resep;
    private javax.swing.JTextField nama_dokter;
    private javax.swing.JTextField nama_obat;
    private javax.swing.JTextField nama_pasien;
    private javax.swing.JLabel nama_user;
    private javax.swing.JTextField no_registrasi;
    private javax.swing.JPanel panel_resep;
    private javax.swing.JTable tabel_resep;
    private javax.swing.JLabel tgl_resep;
    private javax.swing.JTextField total_harga_resep;
    // End of variables declaration//GEN-END:variables
}
